### ISSUE TITLE
ResourceExhaustedError when allocating

### ISSUE THREAD

**Issue by chengxi950921** [dBeker/Faster-RCNN-TensorFlow-Python3#110] opened 2019-10-11 04:41 UTC
ResourceExhaustedError: OOM when allocating tensor with shape[25088,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: vgg_16/fc6/weights/Initializer/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, _class=["loc:@vgg_16/fc6/weights/Assign"], dtype=DT_FLOAT, seed=3, seed2=466, _device="/job:localhost/replica:0/task:0/device:GPU:0"](vgg_16/fc6/weights/Initializer/random_uniform/shape)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by morpheusthewhite** [comment] 2019-10-11 11:59
Duplicate of https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/87

**Closed as completed by morpheusthewhite** 2019-10-11 11:59 UTC
Labels: duplicate
