### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by sunyhaime** [dBeker/Faster-RCNN-TensorFlow-Python3#113] opened 2019-10-17 02:51 UTC
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./data/imagenet_weights/vgg16.ckpt
  File "D:/SUNYUHAI/sunyuhai/Faster-RCNN-TensorFlow-Python3-master/train.py", line 216, in <module>
    train.train()
  File "D:/SUNYUHAI/sunyuhai/Faster-RCNN-TensorFlow-Python3-master/train.py", line 123, in train
    variables_to_restore = self.net.get_variables_to_restore(variables, var_keep_dic)
  File "D:\SUNYUHAI\sunyuhai\Faster-RCNN-TensorFlow-Python3-master\lib\nets\vgg16.py", line 66, in get_variables_to_restore
    if v.name.split(':')[0] in var_keep_dic:
TypeError: argument of type 'NoneType' is not iterable

**Comment by morpheusthewhite** [comment] 2019-10-22 20:04
Duplicate of https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/80

**Closed as completed by morpheusthewhite** 2019-10-22 20:04 UTC
Labels: duplicate
