### ISSUE TITLE
how use resnet to train fasterrcnn ?

### ISSUE THREAD

**Issue by chenjjjjuu** [dBeker/Faster-RCNN-TensorFlow-Python3#108] opened 2019-09-24 07:20 UTC
i can run this script by VGG16 on my data now,but how to use renet101 to train and witch document should be modify?

**Comment by morpheusthewhite** [comment] 2019-09-24 13:56
Duplicate of https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/79

**Closed as completed by morpheusthewhite** 2019-09-24 13:56 UTC
Labels: duplicate, enhancement

**Comment by chenjjjjuu** [comment] 2019-09-30 13:12
DO` you use pascal_voc2007 datasets in this `?

**Comment by morpheusthewhite** [comment] 2019-09-30 14:31
Yes
